parameters:
    mopa_backend.google_analytics.block.service.class: Mopa\Bundle\BackendBundle\Block\GoogleAnalyticsBlockService

services:
    mopa_backend.google_analytics.block.service:
        class: %mopa_backend.google_analytics.block.service.class%
        arguments: ["mopa_backend.google_analytics.block.service", @templating]
        tags:
            - { name: "sonata.block"}
