fng_contact:
    pattern: /contact
    defaults:
        _controller: 'fng_one_page.contact_controller:showAction'

fng_one_page_put_document:
    pattern: "/{_locale}/symfony-cmf/create/draggable/{subject}"
    defaults:
        _controller: cmf_create.rest.controller:putDocumentAction
        _format: json
    requirements:
        subject: .+
        _method: PUT

fng_onepage_sitemap:
    path: /sitemap.{_format}
    defaults:
        _controller: MopaBackendBundle:SiteMap:siteMap
        _format: xml
    requirements:
        _format: xml
        _method: GET